### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by pirate**
Not sure if it's complete since I still got several errors even with all the required packages installed, but it's a start.

Ideally there should also be a `setup.py` to install `python-dev` and the crypto libraries that need to be installed via apt-get.  Would be nice to have some setup instructions or a quickstart in the readme too.

### CODE REVIEW

**Comment by codemunkee** [comment]
I was going to send along the same thing, also probably worth adding dnet, pycrypto, and pcapy.

**Comment by PierrePaul** [comment]
Worked for me, but I'm getting these errors : 

```
Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality
ImportError('cannot import name TLSHandshake',)
```

Not really sure of the impact, might be related to circular import and not related at all to this requirements.txt

**Comment by pirate** [comment]
@PierrePaul those are the same errors I got.

**Comment by pdf** [comment]
See https://github.com/tintinweb/scapy-ssl_tls/commit/951faa4971480cdf2c5eaf5ab91526d6ccaf9f0c for the circular import fix

**Comment by martinseener** [comment]
On OSX El Capitan i was able to use scanner.py by installing the following using Homebrew:
`brew install python` (installs latest 2.7 including pip)
`pip install enum pycrypto scapy scapy-ssl_tls pyasn1`

Afterwards i still get the Import Error like @PierrePaul above but the script actually checks my server then. It's maybe worth adding `pyasn1` to the requirements as well, @pirate

**Comment by nimia** [comment]
Thanks for helping make this tool more accessible, your input is greatly appreciated.
It looks like the updated README.me mentions all relevant dependencies.
I'm aware of this message:
ImportError('cannot import name TLSHandshake',)
that confuses people, and am working on removing it.
Closing this issue for now, please let me know if there are more missing dependencies, or anything that prevents people from using the tool. Thanks!

**Pull request closed without merging**
